version: "3.9"

services:

  web:
    build: .
    env_file: 
      - docker.env
    ports:
      - "8000:5000"
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=flask-blog
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5